# This sample config contains all fields supported by ravenML core and the bbox plugin.
# Plugin specific configuration is located in the plugin field.

dataset: click_test
overwrite_local: True
artifact_path: '~/Desktop/test'
# ec2_no_kill: False
metadata:
    created_by: Carson Schubert
    comments: no thanks
plugin:
    verbose: true
    comet: false
    model: ssd_mobilenet_v2_coco
    optimizer: RMSProp
    # NOTE: if use_default_config is true, hyperparameters are IGNORED
    use_default_config: true
    hyperparameters:
        train_steps: 1000
    